/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package com.example.xyzreader.data.support.graphics.drawable.animated;

public final class R {
    private R() {}

}
