/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package com.example.xyzreader.data.support.v7.cardview;

final class R {
    private R() {}

    private static final class attr {
        private attr() {}

        public static final int cardBackgroundColor = 0x7f02003d;
        public static final int cardCornerRadius = 0x7f02003e;
        public static final int cardElevation = 0x7f02003f;
        public static final int cardMaxElevation = 0x7f020040;
        public static final int cardPreventCornerOverlap = 0x7f020041;
        public static final int cardUseCompatPadding = 0x7f020042;
        public static final int contentPadding = 0x7f02005a;
        public static final int contentPaddingBottom = 0x7f02005b;
        public static final int contentPaddingLeft = 0x7f02005c;
        public static final int contentPaddingRight = 0x7f02005d;
        public static final int contentPaddingTop = 0x7f02005e;
    }
    private static final class color {
        private color() {}

        public static final int cardview_dark_background = 0x7f040027;
        public static final int cardview_light_background = 0x7f040028;
        public static final int cardview_shadow_end_color = 0x7f040029;
        public static final int cardview_shadow_start_color = 0x7f04002a;
    }
    private static final class dimen {
        private dimen() {}

        public static final int cardview_compat_inset_shadow = 0x7f05004a;
        public static final int cardview_default_elevation = 0x7f05004b;
        public static final int cardview_default_radius = 0x7f05004c;
    }
    private static final class style {
        private style() {}

        public static final int Base_CardView = 0x7f0e0008;
        public static final int CardView = 0x7f0e009d;
        public static final int CardView_Dark = 0x7f0e009e;
        public static final int CardView_Light = 0x7f0e009f;
    }
    private static final class styleable {
        private styleable() {}

        public static final int[] CardView = { 0x101013f, 0x1010140, 0x7f02003d, 0x7f02003e, 0x7f02003f, 0x7f020040, 0x7f020041, 0x7f020042, 0x7f02005a, 0x7f02005b, 0x7f02005c, 0x7f02005d, 0x7f02005e };
        public static final int CardView_android_minWidth = 0;
        public static final int CardView_android_minHeight = 1;
        public static final int CardView_cardBackgroundColor = 2;
        public static final int CardView_cardCornerRadius = 3;
        public static final int CardView_cardElevation = 4;
        public static final int CardView_cardMaxElevation = 5;
        public static final int CardView_cardPreventCornerOverlap = 6;
        public static final int CardView_cardUseCompatPadding = 7;
        public static final int CardView_contentPadding = 8;
        public static final int CardView_contentPaddingBottom = 9;
        public static final int CardView_contentPaddingLeft = 10;
        public static final int CardView_contentPaddingRight = 11;
        public static final int CardView_contentPaddingTop = 12;
    }
}
